name: workflow1
on:
  schedule:
    - cron: "50 * * * *"
  workflow_dispatch:
  push:
    branches: 
      - main
jobs:

  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      last_name: Singh
    steps:
      - name: first step
        run: hotname
        continue-on-error: true
      - name: sleep for 30 seconds
        run: |
          sleep 30
          continue-on-error: true
          eco "Firstname is $first_name. Last name is $last_name"
        env:
          first_name: Gagandeep
        if: github.event_name == 'push'
      - name: multline run
        run: |
          echo running a multiline step
          echo mkdir gagandeep
          echo "Firstname is $first_name. Last name is $last_name"
          echo touch file1
        if: runner.os != 'Windows'

  test:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: hotname
      - name: sleep for 30 seconds
        run: sleep 30
      - name: test step
        run: echo job2 run successfully
    needs: build

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: hostname
      - name: sleep for 30 seconds
        run: sleep 30
    needs: test
    if: ${{ always () }} 
