name: workflow1
on: 
  schedule:
    - cron: "30,35 * * * *"
  push:
    branches:
      - main
jobs:
  build-job: 
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: hostname
      - name: sleep for 60 seconds
        run: sleep 60
      - name: multiple run
        run: 
          echo running a multiline step
          echo mkdir hp
          echo touch file1
  job2: 
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: hostname
      - name: sleep for 60 seconds
        run: sleep 60
      - name: test step
        run: 
          echo job2 run successfully
